version: '3'

services:
  db:
    image: postgres:16.1
    container_name: postgres_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=cj-db
    volumes:
      - ./postgres:/var/lib/postgresql/data

  pdAdmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    user: '${UID}:${GID}'
    environment:
      - PGADMIN_DEFAULT_EMAIL=cjdev544@google.com
      - PGADMIN_DEFAULT_PASSWORD=123123
    volumes:
      - ./pgadmin:/var/lib/pgadmin
      - ./pgadmin:/certs/server.cert
      - ./pgadmin:/certs/server.key
      - ./pgadmin:/pgadmin4/servers.json
